### ISSUE TITLE
Join aliases?

### ISSUE THREAD

**Issue by andrewpros** [yii2mod/yii2-moderation#2]
Any support of aliases?

**Comment by ihorchepurnyi** [comment]
Hi, I don't understand your question, do you mean table aliases?

**Comment by andrewpros** [comment]
Yeah, simple case, if i use any of the moderation query functions like approved() and in the same time it is a part of bigger query with joins and it needs aliases then it won't work, no way to change the status attribute i would need to copy it to local libs from vendors and edit manually.

This is simple package so this is actually fine, i just thought i will let you know it isn't suitable for  all queries.
